### ISSUE TITLE
Following "Diffing updates" pseudo code does not generate a valid Signature DB

### ISSUE THREAD

**Issue by 7h3r34lj0hnd03** [commial/experiments#2]
Following the instructions from: https://github.com/commial/experiments/tree/master/windows-defender/VDM does not seem to generate a valid merged signature DB.
While I did not find the specific versions you've mentioned (1.335.1651.0 and 1.335.1657.0), I did find the following versions which had the same base version (1.355.x.x):
* https://web.archive.org/web/20210407035053if_/https://definitionupdates.microsoft.com/download/DefinitionUpdates/VersionedSignatures/AM/1.335.366.0/amd64/mpam-feX64.exe
* https://web.archive.org/web/20210414035038if_/https://definitionupdates.microsoft.com/download/DefinitionUpdates/VersionedSignatures/AM/1.335.799.0/amd64/mpam-feX64.exe
* https://web.archive.org/web/20210421035207if_/https://definitionupdates.microsoft.com/download/DefinitionUpdates/VersionedSignatures/AM/1.335.1297.0/amd64/mpam-feX64.exe

If I understand the pseudo code, it is as follows:
1. extract RMDX resource data from mpavbase.vdm DLLs
2. extract the base signature DB by decompressing the zlib stream from RMDX data (streamBeginOffset: baseRMDX[0x18:0x1C], decompressedSize: baseRMDX[0x1C:0x20]).
3. extract RMDX resource data from mpavdlta.vdm DLLs
4. extract the delta signature DB by decompressing the zlib stream from RMDX data (streamBeginOffset: dltaRMDX[0x18:0x1C], decompressedSize: dltaRMDX[0x1C:0x20]).
5. extract SIGNATURE_TYPE_DELTA_BLOB data from delta signature DB
6. starting from offset of 8 bytes start reading database merging instructions as follows:
    1. X = read 2 bytes (little endian)
    2. copyBytesSize = X & 0x3FFF
    3. if (X & 0x8000) != 0:
        1. baseSignatureDbOffset = read 4 bytes (little endian)
        2. appendedData = baseSignatureDb[baseSignatureDbOffset : baseSignatureDbOffset + copyBytesSize]
    4. else:
        1. appendedData = read copyBytesSize bytes
    5. mergedSinatureDB.append(appendedData)

The generated mergedSinatureDB following the above is not a valid signature DB.

**Comment by commial** [comment]
Hello,

I'm not sure to understand on which part it's actually failing.
Here is the code I use (working on all version I've tested, on several months):

```python
def apply_delta(delta_blob, orig_file_data):
    """Apply the delta information from a delta blob on an original file"""
    out = []
    
    i = 0
    # Likely base version & CRC
    unks = struct.unpack("II", delta_blob[i: i+8])
    i += 8

    while i < len(delta_blob):
        info = struct.unpack("H", delta_blob[i: i + 2])[0]
        i += 2
        if info & 0x7fff == info:
            # Append from DELTA
            out.append(delta_blob[i: i + info])
            i += info
        else:
            # Append from original
            base_offset = struct.unpack("I", delta_blob[i: i + 4])[0]
            i += 4
            size = (info & 0x7fff) + 6
            out.append(orig_file_data[base_offset: base_offset + size])

    return b"".join(out)
```

The signatures to iter on are DELTA_BLOB (signature 115).

**Comment by t-tani** [comment]
Thank you for the excellent write-up! I had the same problem with @7h3r34lj0hnd03 and figured out that I wasn't adding `6` to the size when appending from the original data.

```python
# Append from original
base_offset = struct.unpack("I", delta_blob[i: i + 4])[0]
i += 4
size = (info & 0x7fff) + 6
#                      ^^^
```

How did you figure out this number?

**Comment by commial** [comment]
Hi,
Nice to see it fixes your issue. As a result, I'll close it.

From what I remember, this number is actually the size starting from the beginning of the blob (including the base offset and info).
